version: '3.8'
services:
  backtest_frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backtest_fe
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app
    command: ["npm", "run", "dev"]
